Rriddler
ne4to-DevTeam21/ne4to-backend pull request #1
Opened 2024-06-15 06:18 UTC by rriddler7

add AuthorizationService

2024-06-18 21:08 UTC, obeedril requested changes

2024-06-18 21:08 UTC, obeedril commented on requests/requests.http
Предлагаю не заливать запросы на гит
Так не делают, вроде
Можно в .gitignore, наверное, добавить

2024-06-18 21:08 UTC, obeedril commented on pom.xml
> -            <version>0.9.1</version>
А чем эта версия плоха?

2024-06-18 21:08 UTC, obeedril commented on src/main/resources/application.yaml
> +  #spring:
Пердлагаю не заливать закомментированный код в девелоп тоже.
Потом устанем все это вычищать.

2024-06-18 21:08 UTC, obeedril commented on src/main/java/com/example/nechto/services/UserService.java
> +            // Заменить на свои исключения
В таких случаях лучше не комменты оставлять а TODO, потом искать будет проще

2024-06-18 21:08 UTC, obeedril commented on src/main/java/com/example/nechto/repository/UserRepository.java
> +    List<UserDAO> findAllByLoginOrByEmail(String login, String email);
Не нашла реализацию этого метода и ниже тоже

2024-06-18 21:08 UTC, obeedril commented on src/main/java/com/example/nechto/services/UserService.java
> +public class UserService {
У сервисов, вроде, тоже принято делать интерфейсы

2024-06-18 21:08 UTC, obeedril commented on src/main/resources/application.properties
Предлагаю пока не удалять

2024-06-18 21:08 UTC, obeedril commented on src/main/java/com/example/nechto/repository/UserRepository.java
> +    List<UserDAO> findAllByLoginOrByEmail(String login, String email);
и мне кажется, это очень плохая практика делать метод, который делает либо одно, либо другое

2024-06-18 21:08 UTC, obeedril commented on src/main/java/com/example/nechto/model/UserDAO.java
> +@Builder
А аннотация @Builder тут точно нужна?

2024-06-18 21:08 UTC, obeedril commented on src/main/java/com/example/nechto/model/UserDAO.java
> +@Getter
Посмотрела в учебном проекте, там в ДАО файлах не используются аннотации lombok. И я помню, где-то в курсе он объяснял, почему. Надо поизучать, наверное, эту тему. А пока, может, стоит ориентироваться на учебный проект?

2024-06-18 21:08 UTC, obeedril commented on src/main/java/com/example/nechto/model/UserDAO.java
> +@NoArgsConstructor
Нам тут точно нужен конструктор без параметров?

2024-06-18 21:08 UTC, obeedril commented on src/main/java/com/example/nechto/services/UserService.java
> +    public UserDAO findByName(String name) {
Зачем нам искать пользователя по имени?

2024-06-18 21:08 UTC, obeedril commented on src/main/java/com/example/nechto/services/UserService.java
> +    public void delete(Long id) {
Зачем нам удалять пользователя? При каких обстоятельствах нам нужен этот метод?

2024-06-18 21:08 UTC, obeedril commented on src/main/java/com/example/nechto/services/UserService.java
> +    public UserDAO editUser(UserDAO userDAO) {
Редактирование юзера надо делать, когда будем страницу с личным кабинетом делать. Сейчас это выглядит ка лишний метод. И тоже нет реализации.

2024-06-18 21:08 UTC, obeedril commented on src/main/java/com/example/nechto/repository/UserRepository.java
> +public interface UserRepository extends JpaRepository<UserDAO, Long> {
UserService давай будем использовать для работы с данными юзера, когда будем делать личный кабинет, там у него будет возможность отредактировать что-то. При этом мы еще должны обсудить, что он сможет редактировать, а что нет. Давай не будем раньше времени писать лишние методы.
Методы, которые мы используем для регистрации и авторизации, как мне кажется, должны быть в сервисах и репозиториях регистрации и авторизации.
И в регистрации методы сервисного слоя я напишу сама, от тебя нужны методы, которые взаимодействуют с БД непосредственно(методы слоя репозитория). Кроме этого тебе не надо делать никаких проверок в слое репозитория по регистрации и, например, проверять, email, т.к. в БД я отдам данные уже проверенными после получения их от фонта, просто в репозитории регистрации нужен метод, который кладет сущность User в БД.

2024-06-18 21:08 UTC, obeedril commented on src/main/java/com/example/nechto/repository/UserRepository.java
> +    Optional<UserDAO> findByName(String name);
Этот метод выглядит лишним. Зачем нам искать юзера по имени?

2024-06-23 17:17 UTC, rriddler7 commented
Изменения перенесены в другой пулл реквест

2024-06-23 17:17 UTC, closed without merging